version: '3.8'

services:
  frontend:
    build:
      context: ./react-app
    ports:
      - "80:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./flask-app
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URI=mysql://user:password@db/mydatabase
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Wananny0328
      - MYSQL_DATABASE=mydatabase
    volumes:
      - PT5D_Eathub:/var/lib/mysql
      - ./db-schema.sql:/docker-entrypoint-initdb.d/db-schema.sql

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "127.0.0.1:8080:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - frontend
  #     - backend

volumes:
  PT5D_Eathub:

